[build]
  command = "hexo generate"
  publish = "/public"

[[redirects]]
  from = "/news/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/news/*"
  to = "/admin/"
  status = 301
