<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      Content licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a><br>
      Site design &copy; 2017 Tommy Chen
    </div>
    <div id="footer-links">
      <a href="https://github.com/{{ config.github }}" class="footer-link" target="_blank"><i class="fa fa-github-alt"></i></a>
    </div>
  </div>
</footer>
